spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:~/private;MODE=PostgreSQL
    username: sa
    driverClassName: org.h2.Driver
    password:

log4j.logger.org.hibernate.SQL: info
log4j.logger.org.hibernate.type.descriptor.sql: trace